version: '3'
services:
  backend:
    build:
      context: ./insurance-rest-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./insurance-web-app
      dockerfile: Dockerfile
    ports:
      - 4200:80
